#https://github.com/linuxserver/docker-plex/
#https://hub.docker.com/r/linuxserver/plex
#For Raspberry Pi deployments. Change the tag for other architectures.
---
version: "2"
services:
  plex:
    image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=998  #use "id admin" to set the correct value.
      - PGID=100  #use "id admin" to set the correct value.
      - VERSION=docker
    volumes:
      - /path/to/your/config/plex:/config
      - /path/to/your/Videos:/Videos
      - /path/to/your/Photos:/Photos
      - /path/to/your/Audio:/Audio
    restart: unless-stopped